### PR TITLE
Bug: Windows and Mac Config file location Fixes #39

### LINKED ISSUE #39: Bug: Windows and Mac Config file location
Instead of syscall rely on conventions for where the file should be

### PR DESCRIPTION
**Pull request by petsagouris**
fix: Improve error handling in configuration loading and script execution

### CODE REVIEW

**Comment by petsagouris** [comment]
I tested this in my windows machine and the Ubuntu via WSL inside of it and it works for creating the config now.

File: internal/config/config.go [hunk 1]
```diff
@@ -10,17 +11,37 @@ import (
 var AppConfig Config
 
 func SetConfig() error {
-	cfg, _ := os.UserConfigDir()
-	viper.SetConfigFile(filepath.Join(cfg, "toney", "config.toml"))
+	cfg, err := os.UserConfigDir()
+	if err != nil {
+		return fmt.Errorf("failed to get user config directory: %w", err)
+	}
```
Comment (NucleoFusion) [inline internal/config/config.go]: Yep so here
instead of taking the os.UserConfigDir()
We should instead take the CLI/TUI Defaults for tools. Which I mentioned in #39 .
```go
func GetCfgDir() string {
	switch runtime.GOOS {
	case "linux", "darwin":
		home, _ := os.UserHomeDir()
		return filepath.Join(home, ".config", "cruise")
	case "windows":
		home, _ := os.UserHomeDir()
		return filepath.Join(home, ".cruise")
	default:
		cfg, _ := os.UserConfigDir()
		return cfg
	}
}
```

Similar to this, but instead of `cruise` we have `toney`.
PS: Spliced from another one of my apps

**Review by NucleoFusion — CHANGES_REQUESTED** [review]

**Comment by NucleoFusion** [comment]
Everything else looks good to me.
Once the changes are done, Ill do a confirmation run on my machine and then merge it

**Review by NucleoFusion — APPROVED** [review]
